### ISSUE TITLE
302 redirect does not occur using Owin `IAppBuilder UseCookieAuthentication`

### ISSUE THREAD

**Issue by calebd-anderson** [autofac/Autofac.Mvc.Owin#10] opened 2024-02-05 23:09 UTC
## Describe the Bug
The behavior of `IAppBuilder UseCookieAuthentication` changed after configuring Autofac Mvc Owin. 
- Specifically, the `LoginPath` option:
```
/// <summary>
/// The LoginPath property informs the middleware that it should change an outgoing 401 Unauthorized status
/// code into a 302 redirection onto the given login path. The current url which generated the 401 is added
/// to the LoginPath as a query string parameter named by the ReturnUrlParameter. Once a request to the
/// LoginPath grants a new SignIn identity, the ReturnUrlParameter value is used to redirect the browser back  
/// to the url which caused the original unauthorized status code.
/// 
/// If the LoginPath is null or empty, the middleware will not look for 401 Unauthorized status codes, and it will
/// not redirect automatically when a login occurs.
/// </summary>
```

- A redirect does not occur automatically.

## Steps to Reproduce
Use Autofac Mvc Owin with `IAppBuilder UseCookieAuthentication`.

```c#
public class ReproTest
{
  [Fact]
  public void Repro()
  {
    // looking for ways to create an HTTP client to demonstrate using a unit test
  }
}
```

## Expected Behavior
The original behavior was a 302 is returned from the initial GET request to `localhost`, immediately sending the browser back to the `LoginPath` specified in the `UseCookieAuthentication` options if a cookie is not present.

## Exception with Stack Trace
n/a

## Dependency Versions
Autofac: 8.0
Autofac.Mvc5: 6.1
Autofac.Mvc5.Owin: 6.1
Autofac.Owin: 7.1
Microsoft.AspNet.Mvc: 5.3.0
(generally using latest nuget versions)

## Additional Info
will update as necessary

**Comment by tillig** [comment] 2024-02-05 23:16
> Use Autofac MVC OWIN with IAppBuilder UseCookieAuthentication

Unfortunately, this isn't clear.

The problem is that order is important with the application builder. What does the startup code look like? What other stuff is in that pipeline? Do you have things that aren't quite using OWIN right? Do you have Autofac middleware being injected other than the lifetime scope creation/disposal that gets added?

We don't need literally the whole app and everything in here, but the pipeline you're building is pretty key to the issue.

Finally, I would recommend taking some time to put together a super minimal repro. Not for us - for you. What can you take _out_ of the repro and still see the issue? Is there something (other than Autofac and the cookie auth) that you can pull out and have it suddenly start working? If you _only_ have Autofac and cookie auth, does it still fail? Get it down to the absolute bare minimum. Most of the time these issues come down to folks forgetting they have something like "we scan every type in every assembly in the whole system and try registering them all into the container" type things - it ends up being application code, not Autofac code. Getting down to that minimum possible repro is a huge help in troubleshooting your own issue.

**Comment by calebd-anderson** [comment] 2024-02-05 23:33
Actually, it doesn't look like Autofac Mvc (without Owin) is working correctly either. I am getting:
`You do not have permission to view this directory or page.` if I disable Autofac Mvc Owin and leave the standard https://autofac.readthedocs.io/en/latest/integration/mvc.html configuration alone.

**Comment by tillig** [comment] 2024-02-05 23:37
Sounds like you have some app code problems to work through first, then. I'm going to close this ticket and if it turns out you can actually pinpoint an issue with the Autofac integration after doing a minimal repro, we can either reopen this or we can start a new issue with a more specific description.

**Closed as completed by tillig** 2024-02-05 23:37 UTC

**Comment by calebd-anderson** [comment] 2024-02-06 04:55
Okay, so I misunderstood how to configure [Autofac.WebApi.Owin](https://github.com/autofac/Autofac.WebApi.Owin) as well as [Autofac.Mvc.Owin](https://github.com/autofac/Autofac.Mvc.Owin). I needed to pay closer attention to the [Get the HTTPConfiguration](https://docs.autofac.org/en/latest/integration/webapi.html#get-the-httpconfiguration) section of the `Autofac.WebApi.Owin` docs.
My understanding is, as I am **not self-hosting**, these are not set in the Owin pipeline:
```
app.UseAutofacMvc();
app.UseAutofacWebApi(config);
app.UseWebApi(config);
```
`app.UseWebApi(config);` [expects a self-hosted API](https://learn.microsoft.com/en-us/aspnet/web-api/overview/advanced/configuring-aspnet-web-api#configuring-web-api-with-owin-self-hosting) and because I didn't have one I just got generic 401 from IIS server.
